name: Demo
on:
  #schedule:
  #- cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  demo:
    name: "Demo run"
    runs-on: "ubuntu-latest"
    steps:
      - name: "dump-environment"
        run: |
          printenv
      - name: "oidc-request"
        run: |
          export OIDC_TOKEN=$(curl --silent -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://46427d.id.qa.aembit-eng.com"  -H "Accept: application/json; api-version=2.0" | jq -r '.value' )
          echo $OIDC_TOKEN | base64
          export AEMBIT_TOKEN==$(curl -X POST --silent --location "https://46427d.ec.qa.aembit-eng.com/edge/v1/auth" -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Aembit-ResourceSet: ffffffff-ffff-ffff-ffff-ffffffffffff' --data "{\"clientId\": \"aembit:qa:46427d:identity:github_idtoken:7fa254af-b20b-4fe9-bcdf-b72f3cce3155\",\"client\": {\"github\": {\"identityToken\":\"$OIDC_TOKEN\"}}}" | jq -r '.accessToken')
          echo "AEMBIT TOKEN IS"
          echo $AEMBIT_TOKEN
          CODE=$(curl -X POST --silent --location "https://46427d.ec.qa.aembit-eng.com/edge/v1/credentials" --header "Authorization: Bearer $AEMBIT_TOKEN" -H 'Content-Type: application/json' -H 'Accept: application/json' --data "{\"credentialType\": \"UsernamePassword\", \"client\": {\"gitlab\": {\"identityToken\": \"$OIDC_TOKEN\" } }, \"server\": { \"transportProtocol\": \"TCP\", \"host\": \"myhost\", \"port\": 80 } }" | jq)          
          echo $CODE
