name: Demo
on:
  #schedule:
  #- cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  demo:
    name: "Demo run"
    runs-on: "ubuntu-latest"
    steps:
      - name: "dump-environment"
        run: |
          printenv
      - name: "oidc-request"
        run: |
          OIDC_TOKEN=$(curl --silent -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://46427d.id.qa.aembit-eng.com"  -H "Accept: application/json; api-version=2.0" | jq -r '.value' | base64)
          echo $OIDC_TOKEN
          #export OIDC_TOKEN=$(curl --silent -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://46427d.id.qa.aembit-eng.com"  -H "Accept: application/json; api-version=2.0" | jq -r '.value')
      #- name: "aembit-auth-request"
      #  run: |
      #    echo $OIDC_TOKEN | base64
      #   export AEMBIT_TOKEN=$(curl -X POST --write-out '%{http_code}' --silent --location "https://46427d.ec.qa.aembit-eng.com/edge/v1/auth" -H 'Content-Type: application/json' -H 'Accept: application/json' --data '{"clientId": "aembit:qa:46427d:identity:github_idtoken:7fa254af-b20b-4fe9-bcdf-b72f3cce3155","client": {"github": {"identityToken":$OIDC_TOKEN}}}' | jq -r .'accessToken')
      #    echo "AEMBIT TOKEN IS"
      #   echo $CODE
      #    echo $AEMBIT_TOKEN
      #- name: "aembit-creds-request"
      #  run: |
      #    curl -X POST --write-out '%{http_code}' --silent --location "https://46427d.ec.qa.aembit-eng.com/edge/v1/credentials" --header "Authorization: Bearer $AEMBIT_TOKEN" -H 'Content-Type: application/json' -H 'Accept: application/json' --data '{"client": {"github": {"identityToken": $DEV_OIDC_TOKEN}},"server": {"transportProtocol": "TCP","host": "myhost","port": "80"},"credentialType": "apiKey"}' | jq
      #    echo "CREDS IS"
      #    echo $CODE
