# This is a basic workflow to help you get started with Actions

name: DEMO CLI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  demo:
    name: "Demo run"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download CLI"
        run: | 
           curl -L https://releases.aembit-eng.com/agent/1.24.3328/linux/amd64/aembit_agent_cli_linux_amd64_1.24.3328.tar.gz -o aembit_agent_cli_linux_amd64_1.24.3328.tar.gz
           tar -xzf aembit_agent_cli_linux_amd64_1.24.3328.tar.gz
      - name: "dump-environment"
        run: |
          printenv
      - name: "oidc-request"
        run: |
          export OIDC_TOKEN=$(curl --silent -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://46427d.id.qa.aembit-eng.com"  -H "Accept: application/json; api-version=2.0" | jq -r '.value' )
          echo $OIDC_TOKEN | base64
          $(./aembit --stack-domain qa.aembit-eng.com credentials get --client-id 'aembit:qa:46427d:identity:github_idtoken:7fa254af-b20b-4fe9-bcdf-b72f3cce3155' --id-token "$OIDC_TOKEN" --server-workload-host myhost --server-workload-port 80)
          echo $TOKEN
          
